### ISSUE TITLE
Codespace beta vs Visual Code

### ISSUE THREAD

**Issue by mysoultan** [XpiritBV/CodeToCloud-Source#1]
the codespace still beta and it asks for an early access. it almost 2 days, and I didn't get the access. I have continued working on visual studio code. but some commands can't be done such as the Workshop-Step.. what are the alternative to overcome this challenge?

**Comment by alilengrai** [comment]
Same issue for me. Some commands cannot be executed

**Comment by cdijkstra** [comment]
The path wasn't set correctly in VSCode (it should be `/workspaces/CodeToCloud-Source` instead of `/home/codespace/workspace/CodeToCloud-Source`). This has been fixed. Can you verify if the `Workshop-Step` (or other commands that previously didn't work) can be executed now?
